quotation_admin:
  path: quotation/admin/research/{page}
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::quotationIndex'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'
    page: 1
  requirements:
    page: '\d+'

quotation_admin_pdf:
  path: quotation/admin/pdf_view/{id_quotation}/{firstname} {lastname}
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::quotationPdf'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_email:
  path: quotation/admin/email/{id_quotation}/{id_customer}
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::mailerAction'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'
  requirements:
    id_quotation: '\d+'
    id_customer: '\d+'

quotation_admin_add:
  path: quotation/admin/add
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::add'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_search_customers:
  path: quotation/admin/search/customers/{query}
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::searchCustomers'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_show_customer:
  path: quotation/admin/show/customer/{id_customer}
  requirements:
    id_customer: '\d+'
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::showCustomer'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_show_customer_details:
  path: quotation/admin/show/customer/{id_customer}/details
  requirements:
    id_customer: '\d+'
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::showCustomerDetails'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_ajax:
  path: quotation/admin/{id_customer}/ajax
  requirements:
    id_customer: '\d+'
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::ajaxCarts'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_autocompletion_ajax:
  path: quotation/admin/autocompletion/customer
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::ajaxCustomer'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_show_cart:
  path: quotation/admin/show/cart/{id_cart}
  requirements:
    id_cart: '\d+'
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::showCart'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_autocompletion_ajax_product:
  path: quotation/admin/autocompletion/product
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::ajaxProduct'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_search_products:
  path: quotation/admin/search/products/{query}
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::searchProducts'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_show_product:
  path: quotation/admin/show/product/{id_product}
  requirements:
    id_product: '\d+'
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::showProduct'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_duplicate_cart:
  path: quotation/admin/duplicate/cart/{id_customer}/{id_cart}/{new_id_cart}
  requirements:
    id_customer: '\d+'
    id_cart: '\d+'
    new_id_cart: '\d+'
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::duplicateCart'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_create_new_cart:
  path: quotation/admin/create/new/cart/{id_product}/{id_product_attribute}/{quantity}/{id_customer}/{id_cart}
  requirements:
    id_product: '\d+'
    id_product_attribute: '\d+'
    quantity: '\d+'
    id_customer: '\d+'
    id_cart: '\d+'
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::createNewCart'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_update_product_quantity_cart:
  path: quotation/admin/update/quantity/product/cart/{id_cart}/{id_product}/{id_product_attribute}/{quantity}
  requirements:
    id_cart: '\d+'
    id_product: '\d+'
    id_product_attribute: '\d+'
    quantity: '\d+'
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::updateQuantityProductCart'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_delete_product_cart:
  path: quotation/admin/delete/product/cart/{id_cart}/{id_product}/{id_product_attribute}
  requirements:
    id_cart: '\d+'
    id_product: '\d+'
    id_product_attribute: '\d+'
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::deleteProductCart'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_autocompletion_ajax_discount:
  path: quotation/admin/autocompletion/discount
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::ajaxDiscount'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_search_discounts:
  path: quotation/admin/search/discounts/{query}
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::searchDiscounts'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_show_discount:
  path: quotation/admin/show/discount/{id_cart_rule}
  requirements:
    id_cart_rule: '\d+'
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::showDiscount'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_insert_cart_rule:
  path: quotation/admin/assign/discount/cart/{id_cart}/{id_cart_rule}
  requirements:
    id_cart: '\d+'
    id_cart_rule: '\d+'
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::insertCartRule'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_delete_discount_cart:
  path: quotation/admin/delete/discount/cart/{id_cart}/{id_cart_rule}
  requirements:
    id_cart: '\d+'
    id_cart_rule: '\d+'
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::deleteDiscountCart'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_create_new_quotation:
  path: quotation/admin/create/new/quotation/{id_cart}/{id_customer}/{reference}/{message_visible}/{date_add}/{status}
  requirements:
    id_cart: '\d+'
    id_customer: '\d+'
    reference: '\w+'
    message_visible: '[^\r\n]+((\r|\n|\r\n)[^\r\n]+)*'
    date_add: '^\d\d\d\d-(0?[1-9]|1[0-2])-(0?[1-9]|[12][0-9]|3[01]) (00|[0-9]|1[0-9]|2[0-3]):([0-9]|[0-5][0-9]):([0-9]|[0-5][0-9])$'
    status: '\w+'
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::createNewQuotation'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_show_quotation:
  path: quotation/admin/show/quotation/{id_quotation}
  requirements:
    id_quotation: '\d+'
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::showQuotation'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_update_message_quotation:
  path: quotation/admin/update/message/quotation/{id_quotation}/{message_visible}
  requirements:
    id_quotation: '\d+'
    message_visible: '[^\r\n]+((\r|\n|\r\n)[^\r\n]+)*'
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::updateMessageQuotation'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_update_status_quotation:
  path: quotation/admin/update/status/quotation/{id_quotation}/{status}
  requirements:
    id_quotation: '\d+'
    status: '[^\r\n]+((\r|\n|\r\n)[^\r\n]+)*'
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::updateStatusQuotation'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_delete_quotation:
  path: quotation/admin/delete/quotation/{id_quotation}
  requirements:
    id_quotation: '\d+'
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::deleteQuotation'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'
