# modules/your-module/config/routes.yml
quotation_admin:        #RouteName
  path: quotation/admin #URL
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::quotationIndex'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_search_filters:
  path: quotation/admin/search/{filter}{reference}{oldest}
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::searchQuotationsByFilters'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'
    filter: null
    reference: null
    oldest: null
#    recent: null
  requirements:
    filter: '([a-zA-Z]+)?.+'
    reference: '(\w+)?.+'
    oldest: '((\d){4}-(\d){2}-(\d){2})?.+'
#    filter: '[a-zA-Z]+|(.*?)|\w+'
#    reference: '(.*?)\w+'

quotation_admin_add:
  path: quotation/admin/add
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::add'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_search_customers:
  path: quotation/admin/search/customers/{query}
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::searchCustomers'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_show_customer:
  path: quotation/admin/show/customer/{id_customer}
  requirements:
    id_customer: '\d+'
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::showCustomer'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_ajax:
  path: quotation/admin/{id_customer}/ajax
  requirements:
    id_customer: '\d+'
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::ajaxCarts'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_autocompletion_ajax:
  path: quotation/admin/autocompletion/customer
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::ajaxCustomer'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

