# modules/your-module/config/routes.yml
quotation_admin:        #RouteName
  path: quotation/admin #URL
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::quotationIndex'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_search_filters:
  path: quotation/admin/search/{reference}{status}{filter}{start}{end}
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::searchQuotationsByFilters'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'
  requirements:
    reference: '^[a-zA-Z0-9]{5}|(.*?)'
    filter: '^[a-zA-Z]+|(.*?)'
    status: '^[a-zA-ZÀ-ÿ-. ]*'
    start: '^(\d{4}(\-\d{2}){2})|\_$|(.*?)'
    end: '^(\d{4}(\-\d{2}){2})$|(.*?)'

quotation_admin_add:
  path: quotation/admin/add
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::add'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_search_customers:
  path: quotation/admin/search/customers/{query}
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::searchCustomers'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_show_customer:
  path: quotation/admin/show/customer/{id_customer}
  requirements:
    id_customer: '\d+'
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::showCustomer'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_ajax:
  path: quotation/admin/{id_customer}/ajax
  requirements:
    id_customer: '\d+'
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::ajaxCarts'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_autocompletion_ajax:
  path: quotation/admin/autocompletion/customer
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::ajaxCustomer'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'
