quotation_admin:
  path: quotation/admin/research/{name}/{reference}/{status}/{start}/{end}/{page}
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::quotationIndex'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'
    name: 'AAAAA'
    reference: '00000'
    status: 'AAAAA'
    start: '1000-01-01'
    end: '3000-01-01'
    page: 1
  requirements:
    page: '\d+'

quotation_admin_pdf:
  path: quotation/admin/pdf_view/{id_quotation}/{firstname} {lastname}
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::pdfView'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_add:
  path: quotation/admin/add
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::add'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_search_customers:
  path: quotation/admin/search/customers/{query}
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::searchCustomers'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_show_customer:
  path: quotation/admin/show/customer/{id_customer}
  requirements:
    id_customer: '\d+'
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::showCustomer'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_show_customer_details:
  path: quotation/admin/show/customer/{id_customer}/details
  requirements:
    id_customer: '\d+'
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::showCustomerDetails'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_ajax:
  path: quotation/admin/{id_customer}/ajax
  requirements:
    id_customer: '\d+'
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::ajaxCarts'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_autocompletion_ajax:
  path: quotation/admin/autocompletion/customer
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::ajaxCustomer'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_show_cart:
  path: quotation/admin/show/cart/{id_cart}
  requirements:
    id_cart: '\d+'
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::showCart'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_autocompletion_ajax_product:
  path: quotation/admin/autocompletion/product
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::ajaxProduct'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_search_products:
  path: quotation/admin/search/products/{query}
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::searchProducts'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_show_product:
  path: quotation/admin/show/product/{id_product}
  requirements:
    id_product: '\d+'
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::showProduct'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_create_new_cart:
  path: quotation/admin/create/new/cart
  requirements:
    id_cart: '\d+'
  methods: [POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::createNewCart'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'