# modules/your-module/config/routes.yml
your_route_name:
  path: quotation/admin
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::quotationIndex'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'