services:
  _defaults:
    public: true

  quotation_repository:
    class: Quotation\Repository\QuotationRepository
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
