services:
  _defaults:
    public: true

  quotation_repository:
    class: Quotation\Repository\QuotationRepository
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'

  product_comment_repository:
    class: PrestaShop\Module\ProductComment\Repository\ProductCommentRepository
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'